### ISSUE TITLE
Browse appears to hang when opening file since 0.5

### ISSUE THREAD

**Issue by raymondEhlers** [scikit-hep/uproot-browser#146]
Thanks for this very nice package! Since the browse rewrite in 0.5, when I try to open any root file with browse, it hangs at a blank screen. It presents as a blank screen in the same color as my terminal background, and accepts no inputs, including ctrl-c. The only way I can close it is via `kill` in a separate terminal, which then leaves the terminal in a semi-broken state visually (eg. cursor isn't show anymore, line returns are a bit broken - I recognize this isn't precise, but I recognize it as the same behavior as when some executable is modifying the terminal behavior and closes before it can cleanup).

The combinations that I've tried:

- macOS 12.?: python 3.10 from pyenv, 3.11 from pyenv, 3.10 from conda
- macOS 13.4: python 3.11 from pyenv, 3.11 from conda
- iTerm2 and terminal.app
- Inside and outside of tmux

I tried 0.6.3 (hangs), 0.5 (hangs), and 0.4.2 (works fine)

Based on the consistency of reproduction of my system, I suspect it's not just a quirk of my setup, but somehow a broader issue. I see that there was previously a `--logging` option, but it appears to have been removed in the rewrite, so I'm not sure how to go about debugging. Any ideas on how I can resolve this or go about debugging it? Thanks!

**Comment by raymondEhlers** [comment]
As a brief follow up, I found today that this also occurs on CentOS 7, so it appears not to be macOS specific

**Comment by henryiii** [comment]
Textual now has a debugging mechanism via its devtools. See https://textual.textualize.io/guide/devtools/. Is there something specific about the ROOT files you are opening? I'm a macOS iTerm2 user, and haven't had it hang up.

**Comment by henryiii** [comment]
And can you try another textual app? Frogmouth, trogon, or one of the demos, perhaps? https://github.com/textualize

**Comment by henryiii** [comment]
Ahh, this is an update somewhere. Wiping my environment and reinstalling produces this for me too.

**Comment by henryiii** [comment]
Textual 0.24 works, anything after that seems broken for us.

**Comment by raymondEhlers** [comment]
Thanks for the suggestions!

- frogmouth works fine for me, so textual seems okay
- I was using a complex root file, so tried creating a trivial one, but same result

Based on your updates now, it seems like you're already ahead of me :-)

**Comment by henryiii** [comment]
The test suite is a bit more manageable in it's failure:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/Users/henryschreiner/git/scikit-hep/uproot-browser/src/uproot_browser/tree.py:155: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --full-trace)
=============================================================================================================== 3 passed in 168.64s (0:02:48) ================================================================================================================
Task was destroyed but it is pending!
task: <Task pending name='Task-16' coro=<MessagePump._post_message() running at /Users/henryschreiner/git/scikit-hep/uproot-browser/.venv/lib/python3.11/site-packages/textual/message_pump.py:648> cb=[_chain_future.<locals>._call_set_state() at /usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/futures.py:394]>
sys:1: RuntimeWarning: coroutine 'MessagePump._post_message' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
fish: Job 1, 'pytest' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by henryiii** [comment]
Commenting out `node.expand()` in `load_directory` keeps it from dying. I'm going to suspect it's related to https://github.com/Textualize/textual/pull/2536.

**Comment by henryiii** [comment]
New version of uproot-browser out, could you see if it's fixed?

**Comment by raymondEhlers** [comment]
0.6.4 works great - thanks for your help and the quick fix!
