### ISSUE TITLE
Browser doesn't open xrootd path

### ISSUE THREAD

**Issue by DraTeots** [scikit-hep/uproot-browser#178]
First I wanted to say THANK YOU!!! for developers. This browser is the best thing we had since... (went thinking). But still, this is a really great time saving tools on farms, remote machines, windows wsl2... (went counting). Still,

```bash
uproot-browser browse "root://dtn-eic.jlab.org//work/eic2/EPIC/RECO/24.08.1/epic_craterlake/DIS/CC/5x41/minQ2=100/pythia8CCDIS_5x41_minQ2=100_beamEffects_xAngle=-0.025_hiDiv_1.0000.eicrecon.tree.edm4eic.root"
```

gives

```
Usage: uproot-browser browse [OPTIONS] FILENAME
Try 'uproot-browser browse -h' for help.

Error: Invalid value for 'FILENAME': {prefix!r} must be an exiting path
```

Everything works with uproot itself (i.e. xrootd is installed and works correctly)

```python
import uproot

file = uproot.open("root://dtn-eic.jlab.org//work/eic2/EPIC/RECO/24.08.1/epic_craterlake/DIS/CC/5x41/minQ2=100/pythia8CCDIS_5x41_minQ2=100_beamEffects_xAngle=-0.025_hiDiv_1.0000.eicrecon.tree.edm4eic.root")
print(file.keys())

# Correctly prints file contents
```

I would anticipate that since `uproot-browser` is `uproot` based it would open things that uproot can

**Comment by henryiii** [comment]
This is being confused because we have a simple splitting on `:`. For `tree` and `browse`, the fix is pretty simple, we can just remove this splitting since uproot handles it for us. Hmm, I think this even works for `plot`.

**Comment by henryiii** [comment]
Can you verify by trying `main`?
