### ISSUE TITLE
Fails, dark mode changed in Textual >= 0.86

### ISSUE THREAD

**Issue by jonas-eschle** [scikit-hep/uproot-browser#184]
In Textual >= 0.86, the `dark` [was removed](https://github.com/Textualize/textual/blob/main/CHANGELOG.md#0860---2024-11-16) and instead the "theme" is used, as for example shown [here](https://github.com/Textualize/textual/pull/5087/files/735a99b881837e6ac33f4137807f22436e12e982#diff-9be08248964ada68c2355f921bd741f3baf3e8da05096c413c043f6c6b7c5cd9R219).

I am not very familiar with the internals of uproot-browser, I would have opened a PR already, but I am a bit unsure how the whole theme thing is handled

For completeness: it currently fails when trying to display a branch with `no attribute "dark"`
![image](https://github.com/user-attachments/assets/658eee05-b987-4bba-b6f6-f0cceb2bd94a)

**Comment by henryiii** [comment]
New release out!
