### ISSUE TITLE
Directory names not showing up in `browse`

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/uproot-browser#47]
While looking at [this file (cernbox link, ~200 MB)](https://cernbox.cern.ch/index.php/s/lpS1T3oLI6Dhbnc) with `uproot-browser browse` (version `0.4.0`), I noticed that the names of the directories within the file do not show up, and the file name repeats instead:
```
 📁 FCBEF10A-19D4-E511-83BF-E41D2D08DCA0.root
 ├── 📁
 │   FCBEF10A-19D4-E511-83BF-E41D2D08DCA0.root
 ├── 🌴 Events (40600)
 ├── 📁
 │   FCBEF10A-19D4-E511-83BF-E41D2D08DCA0.root
 ├── 🌴 Events (40600)
 ├── 📁
 │   FCBEF10A-19D4-E511-83BF-E41D2D08DCA0.root
 ├── 🌴 Events (40600)
 ├── 📁
 │   FCBEF10A-19D4-E511-83BF-E41D2D08DCA0.root
 ├── 🌴 Events (40600)
 ├── 📁
 │   FCBEF10A-19D4-E511-83BF-E41D2D08DCA0.root
 ├── 🌴 Events (40600)
 ├── 📁
 │   FCBEF10A-19D4-E511-83BF-E41D2D08DCA0.root
 ├── 🌴 Events (40600)
 ├── 📁
 │   FCBEF10A-19D4-E511-83BF-E41D2D08DCA0.root
 ├── 🌴 Events (40600)
 ├── 📁
 │   FCBEF10A-19D4-E511-83BF-E41D2D08DCA0.root
 ├── 🌴 Events (40600)
 ├── 📁
 │   FCBEF10A-19D4-E511-83BF-E41D2D08DCA0.root
 └── 🌴 Events (40600)
```
The file contains many directories, which themselves contain trees:
```
$ root -l FCBEF10A-19D4-E511-83BF-E41D2D08DCA0.root
root [0]
Attaching file FCBEF10A-19D4-E511-83BF-E41D2D08DCA0.root as _file0...
(TFile *) 0x17ffae0
root [1] .ls
TFile**		FCBEF10A-19D4-E511-83BF-E41D2D08DCA0.root
 TFile*		FCBEF10A-19D4-E511-83BF-E41D2D08DCA0.root
  KEY: TDirectoryFile	myelectrons;1	myelectrons
  KEY: TDirectoryFile	mymuons;1	mymuons
  KEY: TDirectoryFile	mytaus;1	mytaus
  KEY: TDirectoryFile	myphotons;1	myphotons
  KEY: TDirectoryFile	mymets;1	mymets
  KEY: TDirectoryFile	mytriggers;1	mytriggers
  KEY: TDirectoryFile	mypvertex;1	mypvertex
  KEY: TDirectoryFile	mygenparticle;1	mygenparticle
  KEY: TDirectoryFile	myjets;1	myjets
```
I would have expected that the directory names show up next to the 📁 icons, and am not sure why the file name repeats. Is this perhaps some issue specific to this file, or am I misunderstanding what the browser should show?

**Comment by henryiii** [comment]
This line is incorrect:

https://github.com/scikit-hep/uproot-browser/blob/2c0b056af4f3e5c0fac8474a36ad41c5b4bf3a94/src/uproot_browser/tree.py#L93

**Comment by dcervenkov** [comment]
Any progress on this issue? As it is, the browser is unusable for files with directories inside.

**Comment by dcervenkov** [comment]
@matthewfeickert and @henryiii, excellent, thanks!

**Comment by matthewfeickert** [comment]
@dcervenkov There should hopefully be a new release with it out soon too &mdash; c.f. https://github.com/scikit-hep/uproot-browser/pull/70#issuecomment-1282499207. As @henryiii has also put in PR #81, we just need to get PR #82 merged in and then I think that @amangoel185 and @henryiii can make a release.

So if you add yourself to the watchers list on GitHub then you can hopefully be `python -m pip install --upgrade uproot-browser` or `pipx upgrade uproot-browser` in the near future! :)
