### ISSUE TITLE
Necessary to write out textual.log by default?

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/uproot-browser#55]
In [`uproot-browser` `v0.4.0`](https://github.com/scikit-hep/uproot-browser/releases/tag/v0.4.0) after every run a `textual.log` file is written out

https://github.com/scikit-hep/uproot-browser/blob/573b88a2ff07fb7f8772e97a543d94b112d4ecd1/src/uproot_browser/__main__.py#L103-L113

By default a user might not always want a log file being created every time they run `uproot-browser`. Would it be feasible to only keep the log file around if a flag like `--logging` or something is passed?

**Comment by amangoel185** [comment]
If I remember correctly, we were supposed to remove that behaviour once we had the basic functionality in place, but might have missed it. I think having a flag is a good idea, since logging might only be useful for contributors!

@henryiii, what do you think?
