### ISSUE TITLE
Trees in directories showing up in root folder

### ISSUE THREAD

**Issue by dcervenkov** [scikit-hep/uproot-browser#87]
Since v0.4.1, the uproot-browser correctly displays directory names in the side pane. However, the trees that reside in the directories are displayed both inside the directories and in the root path. Compare the two images below from rootbrowser and uproot-browser.

<img width="420" alt="Screenshot 2022-10-24 at 13 17 50" src="https://user-images.githubusercontent.com/23052054/197514672-44f5261b-00b9-4cd5-8bee-2ece881a7213.png">
<img width="380" alt="Screenshot 2022-10-24 at 13 20 24" src="https://user-images.githubusercontent.com/23052054/197514676-c1904ee0-87ad-4390-8ace-e2d61500e5eb.png">

**Comment by henryiii** [comment]
New release out (0.4.2) with the fix!
